import tokeys from 'tokeys'

export default tokeys([
  'PROPERTIES_SEARCH_REQUESTED',
  'PROPERTIES_SEARCH_SUCCEEDED',
  'PROPERTIES_SEARCH_FAILED',
  'PROPERTY_CHANGE',
  'PROPERTY_FETCH_REQUESTED',
  'PROPERTY_FETCH_FAILED',
  'PROPERTY_FETCH_SUCCEEDED',
])
